### ISSUE TITLE
Docker Duplicates Containers

### ISSUE THREAD

**Issue by williamjhyland** [viam-soleng/viam-docker-manager#1]
Running config:
```
{
    "image_name": "ubuntu",
    "repo_digest": "sha256:a80d11b67ef30474bcccab048020ee25aee659c4caaca70794867deba5d392b6",
    "entry_point_args": [
        "sleep",
        "30"
      ]
}
```
I am finding that it creates multiple docker images:

| CONTAINER ID | IMAGE  | COMMAND    | CREATED        | STATUS        | PORTS | NAMES               |
|--------------|--------|------------|----------------|---------------|-------|---------------------|
| 2fd728af97c0 | ubuntu | "sleep 30" | 7 seconds ago  | Up 5 seconds  |       | competent_franklin  |
| ad05b6546f6e | ubuntu | "sleep 30" | 18 seconds ago | Up 17 seconds |       | compassionate_buck  |
| 234e70b26ffe | ubuntu | "sleep 30" | 29 seconds ago | Up 28 seconds |       | gracious_tesla      |

**Comment by thegreatco** [comment]
Fixed in 84e5789c178ff8d6766e8344c872bf307668befe
